# Generated by Django 5.1 on 2024-10-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('espera', 'Espera'), ('preparación', 'Preparación'), ('terminado', 'Terminado')], default='espera', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(through='detalle.DetallePedidos', to='productos.productos')),
            ],
        ),
    ]
