# Generated by Django 5.1 on 2024-10-18 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle', '0003_alter_detallepedidos_pedido_and_more'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detalles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_detalle', to='detalle.detallepedidos')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_pedido', to='pedidos.pedidos')),
            ],
        ),
    ]
