# Generated by Django 5.1 on 2024-10-18 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedidos',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='pedidos.pedidos'),
        ),
        migrations.AddField(
            model_name='detallepedidos',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='productos.productos'),
        ),
    ]
